# Generated by Django 3.1.3 on 2023-06-03 21:17

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import renaultApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('price', models.IntegerField(default=0)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255)),
                ('description', models.TextField(default='descripción aqui')),
                ('model', models.CharField(default='modelo', max_length=20)),
                ('type', models.CharField(choices=[('SU', 'SUV'), ('HB', 'Hatchback'), ('CT', 'Convertible'), ('SD', 'Sedán'), ('DP', 'Deportivo'), ('CO', 'Coupe'), ('MV', 'Minivan'), ('CP', 'Camionetas Pickup'), ('SW', 'Station Wagon')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('password', models.CharField(max_length=128)),
                ('paymentType', models.CharField(choices=[('EF', 'Efectivo'), ('CA', 'Cuenta de ahorros'), ('CD', 'Credito'), ('CT', 'Cuotas')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renaultApp.client')),
            ],
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('password', models.CharField(max_length=128)),
                ('jobTitle', models.CharField(choices=[('GE', 'Gerente'), ('JT', 'Jefe de Taller'), ('VE', 'Vendedor')], max_length=2)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('carName', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renaultApp.car')),
                ('request', models.ForeignKey(default=renaultApp.models.Demand, on_delete=django.db.models.deletion.PROTECT, to='renaultApp.demand')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register', models.IntegerField(default=0)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renaultApp.client')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='descripción aqui')),
                ('startTime', models.DateField()),
                ('car', models.CharField(default='car', max_length=70)),
                ('price', models.IntegerField(default=0)),
                ('request', models.ForeignKey(default=renaultApp.models.Demand, on_delete=django.db.models.deletion.PROTECT, to='renaultApp.demand')),
            ],
        ),
        migrations.AddField(
            model_name='demand',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renaultApp.staff'),
        ),
        migrations.CreateModel(
            name='Concessionaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('gerente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renaultApp.staff')),
            ],
        ),
    ]
