# Generated by Django 3.1.3 on 2023-05-29 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renaultApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flower',
            new_name='Car',
        ),
    ]
