# Generated by Django 3.1.3 on 2023-05-30 08:02

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renaultApp', '0002_auto_20230529_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('paymentType', models.CharField(choices=[('EF', 'Efectivo'), ('CA', 'Cuenta de ahorros'), ('CD', 'Credito'), ('CT', 'Cuotas')], default='EF', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('jobTittle', models.CharField(choices=[('GE', 'Gerente'), ('JT', 'Jefe de Taller'), ('VE', 'Vendedor')], default='VE', max_length=2)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='car',
            name='Type',
            field=models.CharField(choices=[('SU', 'SUV'), ('HB', 'Hatchback'), ('CT', 'Convertible'), ('SD', 'Sedán'), ('DP', 'Deportivo'), ('CO', 'Coupe'), ('MV', 'Minivan'), ('CP', 'Camionetas Pickup'), ('SW', 'Station Wagon')], default='SU', max_length=2),
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(default='descripción aqui'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default='modelo', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
                ('Worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renaultApp.staff')),
                ('carName', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renaultApp.car')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register', models.IntegerField(default=0)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renaultApp.client')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.BooleanField(default=False)),
                ('description', models.TextField(default='descripción aqui')),
                ('startTime', models.DateField()),
                ('endTime', models.DateField()),
                ('Worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renaultApp.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Concessionaire',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('gerente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renaultApp.staff')),
            ],
        ),
    ]
