# Generated by Django 3.1.3 on 2023-05-30 18:10

from django.db import migrations, models
import django.db.models.deletion
import renaultApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('renaultApp', '0003_auto_20230530_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='State',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Worker',
        ),
        migrations.RemoveField(
            model_name='order',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='State',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='Worker',
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default='123', max_length=128),
        ),
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='car',
            field=models.CharField(default='car', max_length=70),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(default='123', max_length=128),
        ),
        migrations.AddField(
            model_name='staff',
            name='username',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renaultApp.client')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renaultApp.staff')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='request',
            field=models.ForeignKey(default=renaultApp.models.Demand, on_delete=django.db.models.deletion.PROTECT, to='renaultApp.demand'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='request',
            field=models.ForeignKey(default=renaultApp.models.Demand, on_delete=django.db.models.deletion.PROTECT, to='renaultApp.demand'),
        ),
    ]
